### ISSUE TITLE
failed to resolve

### ISSUE THREAD

**Issue by CSWinnall** [LeonardoCardoso/Animated-Expanding-ListView#2]

**Comment by LeonardoCardoso** [comment]
@CSWinnall You need to add my maven url on your build.gradle project file, note it's not the app build.gradle.


repositories {
    jcenter()
    maven { url 'https://github.com/leonardocardoso/mvn-repo/raw/master/maven-deploy' }
}

**Comment by CSWinnall** [comment]
Thanks for responding

I am new to this but im trying to learn

i think ive done that but im still getting this error

Error:(26, 13) Failed to resolve: com.leocardz:aelv:1.1

Craig

**Comment by CSWinnall** [comment]
i am figuring it out slowly

**Comment by CSWinnall** [comment]
Ok so to get your example app to work this is what i had to do delete your
dependency and add

compile project(':library')

i assume this means it wont use any file that you update now.

which happened when i changed these imports in main activity

import com.leocardz.aelv.Aelv;
import com.leocardz.aelv.AelvCustomAction;

i also had to make in aelvListViewHolder viewWrap public


i just could not get the other dependency to work.


CRaig

**Comment by LeonardoCardoso** [comment]
@CSWinnall, did you add @aar?

    compile 'com.leocardz:aelv:1.1@aar'

**Comment by thomasm0077** [comment]
I am also getting Failed to resolve: error....

**Comment by thomasm0077** [comment]
I added maven url to my build.gradle....still error....

**Comment by LeonardoCardoso** [comment]
@thomasm0077 Maybe you are running it behind a firewall. I've tested it in three computers, different WIFIs and both worked.

**Comment by jefry06** [comment]
I face the same issue here.
I have followed all of the steps and used public internet connection.

Error:(59, 13) Failed to resolve: com.leocardz:aelv:1.1
